# Generated by Django 3.1.2 on 2022-02-22 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='正文')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('supports', models.PositiveIntegerField(default=0, verbose_name='点赞量')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', related_query_name='feed', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '动态',
                'verbose_name_plural': '动态',
                'db_table': 'feeds',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FeedImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='feeds/%Y/%m/%d/', verbose_name='配图')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='image', to='feeds.feed')),
            ],
            options={
                'verbose_name': 'FeedImages',
                'verbose_name_plural': 'FeedImages',
                'db_table': 'feed_images',
                'ordering': ['-created'],
            },
        ),
    ]
