# Generated by Django 3.1.2 on 2022-02-26 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='tags',
        ),
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(choices=[('0', '点赞'), ('1', '爱心'), ('2', '大笑'), ('3', '惊讶'), ('4', '流汗'), ('5', '愤怒')], default='0', max_length=1, verbose_name='态度')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feelings', related_query_name='feeling', to='feeds.feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feelings', related_query_name='feeling', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '态度',
                'verbose_name_plural': '态度',
                'db_table': 'feelings',
            },
        ),
    ]
