# Generated by Django 3.1.2 on 2022-03-06 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='事件名')),
                ('time', models.DateField(verbose_name='事件执行日期')),
                ('finished', models.BooleanField(default=False, verbose_name='是否完成')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', related_query_name='event', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '事件',
                'verbose_name_plural': '事件',
                'db_table': 'events',
            },
        ),
    ]
