# Generated by Django 3.1.2 on 2022-02-14 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RichTextNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('body', models.TextField(verbose_name='正文')),
                ('avatar', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='articles/%Y/%m/%d/', verbose_name='配图')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('category', models.CharField(choices=[('随笔', '随笔'), ('日记', '日记'), ('心情', '心情'), ('小说', '小说')], default='1', max_length=2, verbose_name='类别')),
                ('supports', models.PositiveIntegerField(default=0, verbose_name='点赞量')),
                ('isPrivate', models.BooleanField(default=False, verbose_name='是否私密')),
                ('isStar', models.BooleanField(default=False, verbose_name='星标')),
                ('isDraft', models.BooleanField(default=False, verbose_name='草稿')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='简介')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', related_query_name='article', to=settings.AUTH_USER_MODEL)),
                ('collectors', models.ManyToManyField(related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='收藏者')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'tb_articles',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='归档名')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('isPrivate', models.BooleanField(default=False, verbose_name='是否私密')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', related_query_name='archive', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '归档',
                'verbose_name_plural': '归档',
                'db_table': 'archives',
                'ordering': ['-created'],
            },
        ),
    ]
