# Generated by Django 3.1.2 on 2022-02-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('随笔', '随笔'), ('日记', '日记'), ('心情', '心情'), ('小说', '小说')], default='随笔', max_length=2, verbose_name='类别'),
        ),
    ]
