# Generated by Django 3.1.2 on 2022-02-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20220214_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='isPrivate',
            field=models.BooleanField(default=True, verbose_name='是否私密'),
        ),
        migrations.AlterField(
            model_name='article',
            name='isPrivate',
            field=models.BooleanField(default=True, verbose_name='是否发布'),
        ),
    ]
