# Generated by Django 3.1.2 on 2022-02-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20220218_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='isPrivate',
        ),
        migrations.RemoveField(
            model_name='article',
            name='isPrivate',
        ),
        migrations.AddField(
            model_name='archive',
            name='isPublic',
            field=models.BooleanField(default=True, verbose_name='是否公开'),
        ),
        migrations.AddField(
            model_name='article',
            name='isPublic',
            field=models.BooleanField(default=False, verbose_name='是否公开'),
        ),
    ]
