# Generated by Django 3.1.2 on 2022-03-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_delete_richtextnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='markdownText',
            field=models.TextField(blank=True, null=True, verbose_name='markdown文本'),
        ),
    ]
