# Generated by Django 3.1.2 on 2022-03-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(default='', max_length=64, verbose_name='用户位置'),
        ),
    ]
